### ISSUE TITLE
Website: Error in Playground

### ISSUE THREAD

**Issue by schickling** [graphql-nexus/schema#169]
https://nexus.js.org/playground

![image](https://user-images.githubusercontent.com/1567498/60334572-223ece00-999c-11e9-8e0c-f68863e7ccd9.png)

**Comment by hazzard1014** [comment]
I guess i got the "same" problem...

I was trying to use the scalar type following the examples/ghost 
some code here: 
```js
import { GraphQLDateTime } from "graphql-iso-date";

export const GQLDateTime = decorateType(GraphQLDateTime, {
  rootTyping: "Date",
  asNexusMethod: "datetime"
});
```

then add backingTypeMap field to typegenAutoConfig option at makePrismaSchema function as below:

```js
backingTypeMap: {
      DateTime: "Date"
    }
```

when I run `yarn dev` which is `ts-node-dev --no-notify --respawn --transpileOnly ./src`,
everthing works, but run start which is `ts-node src/index.ts` got the "same" error like above

```
Property 'datetime' does not exist on type 'ObjectDefinitionBlock<"XXX">'.

     t.datetime("receivedAt", { nullable: false });
```
I'm getting so confused🤔, i dont know what i can do, really need help

**Comment by tgriesser** [comment]
@hazzard1014 is the `GQLDateTime` type imported into the `makeSchema`'s `types`?

Also if you've provided `rootTyping` you shouldn't need to also declare it in the `backingTypeMap` (assuming you're on the latest `0.12.0-beta.6` - will plan on making this an official `0.12.0` this week, once I get a chance to add docs).

**Comment by tgriesser** [comment]
@schickling I'm not actually sure whether the playground is really that useful in its current state. Really doesn't capture the full experience of Nexus - I was considering removing it from the docs. Thoughts?

**Comment by schickling** [comment]
@tgriesser I suggest to replace it with an embedded Codesandbox 💯

**Comment by hazzard1014** [comment]
@tgriesser Thanks for the reply, I'm using Nexus(which is the latest `0.12.0-beta.6`) along with Prisma.
Yes I put the `GQLDateTime` into the `makePrismaSchema` 's types, and I'm using the `nexus-prisma`which the version is `0.3.7`(the latest version). I have tried few changes ,but I feel no progress.

**Comment by jasonkuhrt** [comment]
Hey @hazzard1014 could you share a minimal repo repro?

**Comment by tgriesser** [comment]
I believe this is sorted in the latest `0.12.0-rc.4` & latest `nexus-prisma`. If you are still having issues please comment and we can reopen.

**Comment by schickling** [comment]
Hmm still seems broken to me 🙈 

![image](https://user-images.githubusercontent.com/1567498/68502027-d52f0a80-025f-11ea-9add-4564f3c6cd6c.png)

> Cannot read property 'field' of undefined

**Comment by tgriesser** [comment]
Yeah, it's because it is joining the current line with the next line for some reason - so it thinks it's `t.t.field`. It's fine though, i'll just remove the playground from the docs site, it's not super useful anyway.

**Comment by krejko** [comment]
Unfortunately, I am also having this same problem. Have almost the exact same setup as @hazzard1014, except I'm using `'graphql-scalars'` instead of  `'graphql-iso-date'`

I have also tried declaring this without using any libraries according to the `scalarType` [documentation page](https://nexusjs.org/docs/api/scalar-type), but this also doesn't seem to have any changes.

```
const DateScalar = scalarType({
  name: 'Date',
  asNexusMethod: 'date',
  description: 'Date custom scalar type',
  parseValue(value) {
    return new Date(value)
  },
  serialize(value) {
    return value.getTime()
  },
  parseLiteral(ast) {
    if (ast.kind === Kind.INT) {
      return new Date(ast.value)
    }
    return null
  },
})
```

These scalar types have been added to `makeSchema`'s `types`

I am using hte most recent version of `@nexus/schema` `"^0.17.0"`

**Comment by jasonkuhrt** [comment]
We replaced playground with a codesandbox in https://github.com/graphql-nexus/schema/commit/abed6e001eb2d7fb892652e85fd69b6fcf1789f5
