### ISSUE TITLE
Find more seamless way (ideally zero-config) to register Context type

### ISSUE THREAD

**Issue by schickling** [graphql-nexus/schema#265]
The following is the current way to get a typed context object using Nexus. This feels pretty cumbersome and I'd prefer a zero-config way (while still being transparent) to "register" the Context type.

![image](https://user-images.githubusercontent.com/1567498/66717542-96ca3b00-edda-11e9-93b4-f6dd47d01080.png)

**Comment by Weakky** [comment]
`sources` is a bit misleading/hard to grasp for the context type.
Maybe nexus could have a top-level function such as:

```
{
  contextType: parseType(require.resolve('../context'), 'Context')
}
```

It's not much better, but at least it's "contained" and doesn't require the need to understand the whole `typegenAutoConfig` behavior.

Other options:

- `parseType({ path: "", typeName: "" })`
- `readType(..)`
- `getType(..)`

WDYT?

**Comment by jasonkuhrt** [comment]
Feedback in https://github.com/prisma/prisma-examples/pull/867 raises a question about the workflow around this config between build stages.

**Comment by jasonkuhrt** [comment]
Zero config can be achieved with a framework. I think @Weakky's approach is an improvement.

I cannot think of a good zero config design that feels appropriate at the library level which Nexus is.

**Comment by tgriesser** [comment]
Yeah, I agree this should be changed. Will look to get it in as part of the final pass for 0.12 changes.

**Comment by jasonkuhrt** [comment]
I have a multi-sourced context issue here: https://github.com/prisma-labs/nexus/issues/323. How that might look with the APIs sketched in this issue:

```ts
type ContextTypeProperty = 
	| { path: string, typeName?: string, alias?: string }
	| Array<{ path: string, typeName?: string, alias?: string }>
```
