### ISSUE TITLE
Relay connection extension should follow pagination algorithm

### ISSUE THREAD

**Issue by Weakky** [graphql-nexus/schema#267]
## Description

Current plugin `t.relayConnection` leaves the `pageInfo` implementation to the user.
There should at least be a default which follows relay official spec. That would result in `pageInfo(...)` being optional.

https://facebook.github.io/relay/graphql/connections.htm#sec-undefined.PageInfo.Fields

https://github.com/graphql/graphql-relay-js/blob/677e6cc50b1bd53433ef10b289417eaf1056013c/src/connection/arrayconnection.js

Suggestion:
- Maybe the `t.relayConnection` plugin should leave in its own npm package, and should use `graphql-relay` under the hood. That's probably the best way to stay up-to-date to the relay spec

**Comment by JCMais** [comment]
This probably can be closed as there is a simple pageInfo configuration now
