### ISSUE TITLE
Plugin: Connection Type

### ISSUE THREAD

**Issue by tgriesser** [graphql-nexus/schema#314]
Related: #22, #280, #218, #267

Now that plugins are generally available in 0.12.0-rc.4, we should use them to ship a stable abstraction for connections, a common pain point for anyone building a GraphQL schema.

The plan is that these will have a sensible default:

```ts
makeSchema({
  plugins: [
    connectionPlugin()
  ]
})
```
Which will add a `t.connectionField(...)` implementing the [relay cursor specification](https://facebook.github.io/relay/graphql/connections.htm), but the plugin will be configurable via an `options` object to customize much further for use cases which do not follow this pattern exactly, or extend the types. 

I have something prototyped for this which looks like it will work well, will follow up with a PR in the next few days.

**Comment by JCMais** [comment]
@tgriesser I suppose this issue can be closed as the plugin already exists
