### ISSUE TITLE
Deploying to AWS Lambda

### ISSUE THREAD

**Issue by ryands17** [graphql-nexus/schema#328]
I am currently facing an issue whilst deploying to AWS lambda. I have used the `nexus-prisma` example from the examples directory and deployed using the serverless framework.

After deploying and accessing the playground, this error is logged in Cloudwatch: 
`EROFS: read-only file system, unlink '/var/task/node_modules/@types/nexus-prisma-typegen/index.d.ts'`

![image](https://user-images.githubusercontent.com/19697099/69325414-22ec3f80-0c70-11ea-814e-ee75468148b4.png)

Do we need to add any separate configuration for lambdas?

**Comment by guerrerocarlos** [comment]
@ryands17 to prevent this error just pass `{shouldGenerateArtifacts: false}` in the options you provide to `nexusPrismaPlugin(options)`:

Example:
```js
const schema = makeSchema({
  types: [Query, Mutation, Post, User],
  plugins: [nexusPrismaPlugin({
    shouldGenerateArtifacts: false
  })],
  outputs: {
    schema: __dirname + '/generated/schema.graphql',
    typegen: __dirname + '/generated/nexus.ts',
  },
  typegenAutoConfig: {
    contextType: 'Context.Context',
    sources: [
      {
        source: '@prisma/client',
        alias: 'prisma',
      },
      {
        source: require.resolve('./context'),
        alias: 'Context',
      },
    ],
  },
})
```

**Comment by ryands17** [comment]
Yeah that works!
I'm try for an automated solution to set it to `false` while deployment.

**Comment by langer** [comment]
If google has brought you here for this error and the fix above doesn't seem to work, you may wish to ensure the plugin version you're running matches the [latest version of the documentation](https://nexus.js.org/docs/api-makeschema#shouldgenerateartifacts-outputs-typegenautoconfig) — as of this writing the flag has been moved out of the plugins array, and now appears at the top level of `makeSchema`: 

```
makeSchema({
  types,
  shouldGenerateArtifacts: process.env.NODE_ENV === 'development'
  ...
})
```

I had the same error as @ryands17 above, and this configuration tweak allowed me to get past it.

**Comment by sreuter** [comment]
@langer Does this still work with you with nexus 1.0.0? I've tried the same thing, but unfortunately still get the error.

**Comment by langer** [comment]
@sreuter now the original is what's working for us: 
```
  plugins: [
    nexusSchemaPrisma({
      shouldGenerateArtifacts: true,
    }),
  ],
```

**Comment by aeharake** [comment]
> If google has brought you here for this error and the fix above doesn't seem to work, you may wish to ensure the plugin version you're running matches the [latest version of the documentation](https://nexus.js.org/docs/api-makeschema#shouldgenerateartifacts-outputs-typegenautoconfig) — as of this writing the flag has been moved out of the plugins array, and now appears at the top level of `makeSchema`:
> 
> ```
> makeSchema({
>   types,
>   shouldGenerateArtifacts: process.env.NODE_ENV === 'development'
>   ...
> })
> ```
> 
> I had the same error as @ryands17 above, and this configuration tweak allowed me to get past it.

I'm not using nexus and getting this error. 

btw, who else would bring us here other than Google? :p

**Comment by janpio** [comment]
> I'm not using nexus and getting this error on Google Cloud's App Engine

That would be a case for an issue in https://github.com/prisma/prisma/issues then 👍
