### ISSUE TITLE
Auto-resolve nearest Prettier configuration

### ISSUE THREAD

**Issue by kripod** [graphql-nexus/schema#341]
In order to reduce the amount of configuration required by Nexus, the `prettierConfig` option could be resolved automatically to the nearest [`.prettierrc{.{json|yaml|yml|js|toml}}?` or `prettier.config.js`](https://prettier.io/docs/en/configuration.html) file by searching in parent directories recursively.

For discovery and loading, [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) may be used.

**Comment by jasonkuhrt** [comment]
Hey @kripod I will leave this open for now, but pretty sure it will not get addressed at the nexus library level. Reducing the required configuration is not a  goal of nexus. This feature would be appropriate for higher order tooling.

**Comment by kripod** [comment]
Is there any specific kind of higher level tooling planned or available? May this be the purpose of [yoga2](https://github.com/prisma-labs/yoga2)?

**Comment by jasonkuhrt** [comment]
@kripod Yep we're actively prototyping things at Prisma Labs right now. Not ready to share yet.

**Comment by jasonkuhrt** [comment]
Reducing configuration at the level of Nexus Schema is no longer a primary goal. The feature request here is out of scope. `nexus` would be a tool that cares about this kind of thing.
