### ISSUE TITLE
Access field resolve function directly

### ISSUE THREAD

**Issue by Nayni** [graphql-nexus/schema#346]
Lately I've been iterating on better ways to test what I call "native" GraphQL implementations, with this I mean a GraphQL backend implementation that isn't just wrapping existing services but instead if built directly on top of GraphQL, and thus resolvers that contain up to certain level of logic.

I've been going back and forth between code first and schema first approaches, one of the main benefits that I've noticed lately with schema first approaches is that testing logic inside a resolver is insanely simple. This is because the resolvers are usually just a simple object of plain old functions. This makes them very testable in isolation. 

However going to a code first approach this actually becomes more tedious, especially in nexus's case, the resolve is part of a config that is warpped in several function calls (so that nexus can do its magic) but this makes testing a single resolver to be more tedious... I've found that I have to resort to the following work-around's to test them:

- I create the entire schema in my test suite and perform a query against the field I wish to test it's resolver for. This is quite tedious because I have to spin up a lot of boilerplate, just to test a single function.
- I define my resolver separately and attach it in the resolve config. This is the "better" solution, but it requires me to always find a good place and/or name to put them somewhere. I feel like this solution is the better one out of the two, but I would prefer to not repeat myself and just create the resolve inline with the type definition, it keeps everything co-located nicely and gives all the context at once, which is one of the benefits for code-first approaches imho.

This got me thinking, if it would be possible to create some sort of extra API in nexus allowing the access to a field definition without letting it pass through the internals of nexus. The resolve function still remains a simple inline function so I'm wondering how hard it could be to just expose it out in some form that doesn't require a `makeSchema` invocation.

I was thinking something along the lines of: 

```typescript
export const UserType = objectType({
  name: "User",
  definition(t) {
    t.id("id");
    t.list.field("posts", {
      type: "Post",
      resolve: (user, args, context, info) => {
        // getPosts...
      }
    });
  }
});

UserType.getFieldDefinition("posts").resolve // resolve being the function here, which I can directly invoke.
```

This would open up the nexus types to be a lot more testable without ceremony. 
Thoughts?

**Comment by Nayni** [comment]
Took the time to make a small prototype of what I had in mind and actually got the following to work:

```typescript
// Helper type to return the standard FieldDefinition fields as well as only include the resolve function if the type had one defined using the built-in NeedsResolver helper.
export type FieldDefinition<
  TypeName extends string,
  FieldName extends string
> = NeedsResolver<TypeName, FieldName> extends true
  ? {
      resolve: FieldResolver<TypeName, FieldName>;
    } & Omit<NexusOutputFieldDef, "resolve">
  : Omit<NexusOutputFieldDef, "resolve">;


function getFieldDefinition<
  TypeName extends keyof NexusGenFieldTypes,
  FieldName extends Extract<
    keyof NonNullable<NexusGenFieldTypes[TypeName]>,
    string
  >
>(nexusType: NexusObjectTypeDef<TypeName>, fieldName: FieldName) {
  const fields: NexusOutputFieldDef[] = [];
  const config = nexusType.value;

  // Fake definition block just so we can collect the definition.
  const definitionBlock = new ObjectDefinitionBlock<TypeName>({
    typeName: config.name,
    warn: () => {}, 
    addInterfaces: () => {}, // duno if we need this
    addDynamicOutputMembers: () => {}, // duno if we need this
    addField: fieldDef => fields.push(fieldDef)
  });

  config.definition(definitionBlock);

  const field = fields.find(f => f.name === fieldName);
  
  // Needs improvement...
  if (!field) {
    throw new Error("No field :(");
  }
  
  // Cast to FieldDefinition type for better type support.
  return (field as unknown) as FieldDefinition<TypeName, FieldName>;
}
```

This is sufficient to extract the fields its definitions, resolve function included and properly type checked.

```typescript
// Given the following types:
export const UserType = objectType({
  name: "User",
  definition(t) {
    t.id("id");
  }
});

export const QueryType = queryType({
  definition(t) {
    t.field("me", {
      type: "User",
      resolve: () => {
        return {
          id: "1"
        };
      }
    });
  }
});

// The following can be extracted:
const queryMeFieldDef = getFieldDefinition(QueryType, "me");
queryMeFieldDef.resolve // FieldResolver<"Query", "me">

const userIdFieldDef = getFieldDefinition(UserType, "id");
userIdFieldDef.resolve // undefined
```

**Comment by tgriesser** [comment]
> I've been going back and forth between code first and schema first approaches, one of the main benefits that I've noticed lately with schema first approaches is that testing logic inside a resolver is insanely simple. This is because the resolvers are usually just a simple object of plain old functions. This makes them very testable in isolation.

For testing GraphQL schemas generally speaking, I use some a [graphql-code-generator](https://graphql-code-generator.com/) template which takes test `.graphql` files and converts them into executable test functions:

```graphql
query Test_me {
  me {
    id
    name
    avatar
  }
}
```

```ts
const obj = setupTestDataContext()

describe('Query.me', () => {
  test('utilizes the current user object', async () => {
    const initial = await obj.scenarios.setupOrgMember()
    const testMe = await gqlSchemaTests(initial).query.me({})
    expect(testMe.body.data).toEqual({
      me: {
        id: initial.user.uuid,
        name: initial.user.name,
        avatar:
          'https://via.placeholder.com/150',
      },
    })
  })
})
```

I'd like to get it cleaned up a bit to share, but here's a rough sketch of it if you're interested: https://gist.github.com/tgriesser/6dbd5cae8e80dbf5fe0d7270cdacda7f

Otherwise though, I typically never have a resolver function that is more than 3 or 4 lines - anything bigger lives as a custom property on the `context` object, and is testable/usable in isolation. I could write more about this pattern in the documentation, but it looks something like [the ghost example](https://github.com/prisma-labs/nexus/tree/cd2599825990ad2258d48e9ca2bf8447b88ff8e2/examples/ghost/src/data-sources), except we use a getter with a [`cacheResult` decorator](https://gist.github.com/tgriesser/dd81e1cc44acfb4c690ff598e5c54afc) which lazily caches the result in place of the class getter when invoked.

So for the Ghost example, something more like:


```ts
import { PostSource } from "./PostSource";
import { UserSource } from "./UserSource";
import { AuthSource } from "./AuthSource";

export class Context {
  constructor(protected config) {} 

  @cacheResult
  get auth() {
    return new AuthSource(this);
  }
  
  @cacheResult
  get post() {
    return new PostSource(this);
  }
  
  @cacheResult
  get user() {
    return new UserSource(this);
  }

  get knex() {
    return this.config.knexFn;
  }
}
```


```ts
t.field('post', {
  type: Post,
  authorize: () => ctx.auth.viewerCanSeePost(root.id),
  resolve(root, args, ctx) {
    return ctx.post.byId(root.id)
  }
}
```

I think exposing the resolver is an interesting idea though, will need to think more about it and whether there are any potential issues based on how the schema generation works/may change internally in the future.

**Comment by Nayni** [comment]
Hmm, the code generator template is a pretty interesting approach I might have to look into.

I can also follow your thought on the fact resolvers shouldn't be that big and that most logic should live in some datasource/service/storage/loader. However the resolver still contains some "orchestration" logic, for example creating a new Post will require fetching the user via the user's datasource first and ensuring the user exists to then call into the post data source to create a new post for that specific user. There are cases where I still want to test this "orchestration" logic. In that case having access to the resolver directly could make this very easy and would also ease up injecting certain mocks/stubs to 3rd party services that might need to be called in the process.

Will explore the code generated idea a bit more too to see what I can achieve with it.

**Comment by tgriesser** [comment]
> However the resolver still contains some "orchestration" logic, for example creating a new Post will require fetching the user via the user's datasource first and ensuring the user exists to then call into the post data source to create a new post for that specific user.

We actually separate mutations from reads into `DataActions`, which live as a property on and back-reference the `DataContext`, but follow the same pattern - so all of the logic you described, again, would be abstracted from the GraphQL implementation:

```ts
export const createPost = mutationField(
  'createPost',
  {
    type: 'Post',
    description: 'Creates a new Post for a thread',
    authorize: (_, args, ctx) =>
      ctx.authorize.viewerCanCreatePost({ threadId: args.threadId }),
    args: {
      threadId: intArg({ required: true }),
    },
    resolve: async (_, args, ctx) => {
      return ctx.actions.post.createPost(args)
    },
  }
)
```

Then you could mock/stub anything you need and test the `createPost` directly. But we typically just use the codegen and graphql execution directly, as it better tests the entire contract, not just the data source.

**Comment by Nayni** [comment]
The actions concept is a pretty interesting idea. Although I am not a fan of the back-reference to the context object (because it promotes circular dependencies between features).

Just out curiosity would you have a gist of how creating such a `DataAction` would look like? (and how it's connected/backreferenecd with the context?)

**Comment by gustawdaniel** [comment]
I am interesting too. Especially from where should I import `ObjectDefinitionBlock`?

**Comment by Nayni** [comment]
> I am interesting too. Especially from where should I import `ObjectDefinitionBlock`?

I'm not sure if this is still exported since the the move to `@nexus/schema

**Comment by Nayni** [comment]
Going to close this issue, lots of good arguments for both ways, I personally also never pursued this approach further.
