### ISSUE TITLE
Improve error messages on unexpected errors

### ISSUE THREAD

**Issue by steebchen** [graphql-nexus/schema#374]
The error message here is extremely hard to read. It should be simplified, probably in a generic way (for all kinds of error messages, not just this specific one).

<img width="908" alt="image" src="https://user-images.githubusercontent.com/5013932/74088058-b6d9e480-4ac4-11ea-8bd2-286972fffcf9.png">

**Comment by Weakky** [comment]
This doesn't seem related to nexus but to the Prisma Client JS. It's extremely hard to read because the client adds colors to the error message. I don't think it's nexus' responsibility to strip out ansi escape codes from the error message

**Comment by Weakky** [comment]
Will consider above answer sufficient, closing now
