### ISSUE TITLE
Question: Adding a field to generated root type.

### ISSUE THREAD

**Issue by pckilgore** [graphql-nexus/schema#375]
First thanks for the library!  I'm really enjoying my first resolver-first graphql experience and I think it has a lot to do with the composibility nexus allows. 

I'd like to supplement nexus' internal typegen for `root` type in a field resolver.

I'm working with TypeORM + Nexus where the true ID of types are masked in graphql.  

Simplified Example:
```ts
export const PostType = objectType({
  name: "Post",
  definition(t) {
    t.id("uuid");
    t.string("body");
  },
});

export const postQuery = queryType({
  definition(t) {
    t.field("post", {
      type: PostType,
      args: { uuid: idArg({ required: true }) },
      resolve: async (_, { uuid }, { loaders }) => {
        return getRepository(Post).findOne({where: { uuid }});
      },
    });
  },
});
```

```ts
@Entity()
export default class Post {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ type: "text", default: "someIDGenFunction()" })
  uuid: string;

  @Column({ type: "text" })
  body: string;
}
```

When I query `post` I get a record that looks like `{ id, uuid, body }`.  Note the `id` field that is here, that is not on the `PostType`.  This is the hidden internal `id` we don't want to expose to the graph.  

This is fine until I need to consume the `id` in a field resolver (for us, implementing `data-loader`).

Imagine using data loader to get an imaginary field `tags: [Tag]!`:

```ts
export const PostType = objectType({
  name: "Post",
  definition(t) {
    t.id("uuid");
    t.string("body");
    t.field("tags", {
      resolve: (root, _, { loaders }) => loaders.tagsByPostId.load(root.id);
    });
  },
});
```

This throws a type error because nexus does not think they type of `root` has a field `id`, even though it *is* there.

Is there a way I can tell nexus that certain types in my schema have these hidden fields that can only be accessed server side like the data-loader example above?

I suspect `typegenAutoConfig` might be the way to do this, but I could not determine *how* to do it from the examples (and I don't want to hand-write type definitions that TypeORM gives me for free).

Thank you!

**Comment by pckilgore** [comment]
So here's my way to bandage over the issue,  but it would still be ideal if I could tap into the typeGen to add this id field to all the types automatically rather than writing these types myself (but this is way better than what I was about to do!).

```ts
import { NexusGenRootTypes } from "../../generated/schemaTypes";
type PostRoot = NexusGenRootTypes["Post"] & { id?: number };

export const PostType = objectType({
  name: "Post",
  definition(t) {
    t.id("uuid");
    t.string("body");
    t.field("tags", {
      resolve: (root: PostRoot, _, { loaders }) => loaders.tagsByPostId.load(root.id);
    });
  },
});
```

**Comment by lvauvillier** [comment]
Hi @pckilgore, you're right, you have to use `typegenAutoConfig` to add sources for your backing root types.
There is a discussion on this at issue #277

**Comment by tgriesser** [comment]
See also https://github.com/prisma-labs/nexus/issues/36#issuecomment-463649216 and https://github.com/prisma-labs/nexus/issues/139#issuecomment-494048131

Better docs are on the todo list.

**Comment by pckilgore** [comment]
@lvauvillier @tgriesser Thanks, I'll take a look.  

If I have questions, is there a preferred pathway to ask questions over github issues?

**Comment by pckilgore** [comment]
For anyone that finds this later, the pattern that gets you there is:

```ts
import * as types from "types/";

export const schema = makeSchema({
  types,
  outputs: { /* ...  * /},
  typegenAutoConfig: {
    sources: [
      { 
        alias: "PostRootType", 
        source: path.join(__dirname, "entities", "Post.ts"
      }
    ]
  }
});
```

And where, **and this tripped me up** the Post typeORM entity was a named export from the file and not a default export.

This is really sweet, thanks @tgriesser  and team.
