### ISSUE TITLE
`data` is null when an error has been thrown instead of nulling the query

### ISSUE THREAD

**Issue by kevinwolfdev** [graphql-nexus/schema#383]
As opposed to ApolloServer recommendations on returning null for the query instead of nulling the `data` object:

![Apollo convention](https://www.apollographql.com/docs/apollo-server/c2c1c70961654ecfa89213ff1c10fa30/error-code.png)

`queryField` is nulling the `data` object instead of `data.wizard` property:

![Screenshot 2020-02-18 at 11 48 05](https://user-images.githubusercontent.com/3157426/74763060-ac49e880-5244-11ea-9787-fab452fef549.png)

Which is causing me errors when working with other libraries like `urql` that expects the `data` property to be an object instead of `null`.

This is the codesandbox where I implemented it: https://codesandbox.io/s/wizards-api-cu8wv

**Comment by iamkevinwolf** [comment]
As a temporary solution, I am adding a `formatResponse` function to Apollo server.

```ts
const server = new ApolloServer({
  context,
  schema: applyMiddleware(schema, permissions),
  playground: process.env.NODE_ENV === 'development',
  formatResponse: (response, { operationName }) => {
    if (response && operationName) {
      return {
        ...response,
        data: response.data || {
          [operationName]: null,
        },
      }
    }

    return {
      data: null,
    }
  },
})
```
