### ISSUE TITLE
Ability to specify nullability of connectionPlugin output

### ISSUE THREAD

**Issue by swac** [graphql-nexus/schema#384]
Right now there's no way to specify whether or not a connection field is nullable via the plugin. It seems to follow the value of the schema's `nonNullDefaults.output` setting right now.

It'd be nice to able to specify the nullability of both the connection and the inner `edges` (and `nodes`) fields. This seems to matter more when `nonNullDefaults.output` is `false`, since it leads to types like:

```graphql
type SomeType {
  someConnection: SomeConnection
}

type SomeConnection {
  edges: [SomeEdge]
  nodes: [SomeNode!]
  pageInfo: PageInfo!
}

type SomeEdge {
  node: SomeNode
  cursor: String!
}
```

This forces the client to check for nullability on `someConnection`, `someConnection.edges`, and `someConnection.edges[0]`.

If anyone has guidelines on what a good solution would be here, I'd be happy to send a PR 😄

**Comment by venikx** [comment]
I ran into the same issue. On the client we end up doing the following:
```typescript
        client.query({
            query: getSomeConnection,
          })
          .then(r =>
            r.data.someConnection?.edges?.map(edge => ({
              id: edge?.node.id || 0,
              display: edge?.node.name || '' ,
            }))
```

This is not ideal, because, I know for a fact when the edges are not an empty array, the values inside it will never be null. Neither will the node inside the edge.

**Comment by AndresRodH** [comment]
Just stumbled with this too. IMO It feels wrong to have edges be null when `nodes` is treated as non-nullable list of non-null `Node` by default.
