### ISSUE TITLE
Can interfaceType() implement another interface?

### ISSUE THREAD

**Issue by behalka** [graphql-nexus/schema#389]
Hi all,
I have a question - can the `interfaceType()` implement another interface? The GraphQl spec allows it ([details here](https://github.com/graphql/graphql-spec/pull/373)).

Example:

```js
const interfaces = {
  IProfile: interfaceType({
    name: 'IProfile',
    definition(t) {
     // throws "Property 'implements' does not exist on type 'InterfaceDefinitionBlock<"IProfile">"
     t.implements('Node')
    }
}
```

My use case is to add the basic `Node` interface into another one. Not exactly blocking or anything but it would be nice :) 

Also, I'd like to take this opportunity to thank you for this amazing library :)) Sometimes we have to fight the generated typings a little bit but in general, it works like a charm 🙏 👏

**Comment by tgriesser** [comment]
> I have a question - can the interfaceType() implement another interface? The GraphQl spec allows it (details here).

Ah neat, I remember this being a proposal but didn't know it landed. Looks like it's supported in th 15.x rc's, will look to add this in there

> Also, I'd like to take this opportunity to thank you for this amazing library :)) Sometimes we have to fight the generated typings a little bit but in general, it works like a charm 🙏 👏

Awesome, glad to hear you're enjoying it!

**Comment by Mika83AC** [comment]
I'd also highly appreciate to have the possibility to "bundle" multiple interfaces into a "higher level" interface. This would remove many many code duplication.

Any progress on this topic since February?
