### ISSUE TITLE
GraphQLServer schema error

### ISSUE THREAD

**Issue by lglie** [graphql-nexus/schema#407]
import { queryType, stringArg, makeSchema } from "@nexus/schema";
import { GraphQLServer } from "graphql-yoga";

const Query = queryType({
  definition(t) {
    t.string("hello", {
      args: { name: stringArg({ nullable: true }) },
      resolve: (parent, { name }) => `Hello ${name || "World"}!`,
    });
  },
});

const schema = makeSchema({
  types: [Query],
  outputs: {
    schema: __dirname + "/generated/schema.graphql",
    typegen: __dirname + "/generated/typings.ts",
  },
});

const server = new GraphQLServer({
  schema,
});

server.start(() => `Server is running on http://localhost:4000`);

schema error:
Type 'nexusgraphqlschema' cannot be assigned to type 'graphqlschema | undefined'

**Comment by alexvilchis** [comment]
I have this too. Using schema version `0.12`

**Comment by alexvilchis** [comment]
Has there been any update on this issue? It is preventing me from deploying an update to my backend.

**Comment by jasonkuhrt** [comment]
I don’t follow the error here. Could you post a minimal repro that I could check out?

**Comment by alexvilchis** [comment]
@jasonkuhrt  I believe it is the same as [#588](https://github.com/graphql-nexus/nexus-schema-plugin-prisma/issues/588)

**Comment by tgriesser** [comment]
Commented in that issue, it's likely due to the fact that `graphql-yoga` has `graphql` as a `dependency` rather than a `peerDependency`, and so you have two separate copies of GraphQL installed in your project. See my comment in [#588](https://github.com/graphql-nexus/nexus-schema-plugin-prisma/issues/588)
