### ISSUE TITLE
Update GraphQL to v15

### ISSUE THREAD

**Issue by Moumouls** [graphql-nexus/schema#410]
GraphQL get a major release with v15.
GraphQL tools/utlis are gradually moving to the new version.
v15 `GraphQL Schemas` will break with v14 `GraphQL Schemas` when they are merged.

What do you think about this ?

**Comment by Sytten** [comment]
Would be very nice to see this lands, version is now 15.1.0.

**Comment by Moumouls** [comment]
It seems now that `graphql` is listed as a peer dependency, so if you encounter some issues like GraphQL version mismatch, just update to the last version of nexus.

**Note: if you have `nexus` package listed into your package.json, you probably need to migrate your dep.**

1. Remove `nexus` dep
2.  Install the new nexus dep `yarn add @nexus/schema` or `npm i @nexus/schema`
3.  Replace all `nexus` (`import` or `require`)  with `@nexus/schema`

And then you should be right 👍

**Comment by Sytten** [comment]
Still annoying that its not listed in the peer deps as compatible, I didn't see any error though. I will try to run the tests with 15.1 and see if everything passes, maybe its just a matter of updating the package.json.
