### ISSUE TITLE
Nexus prisma example link is broken

### ISSUE THREAD

**Issue by valecarlos** [graphql-nexus/schema#417]
The link provided on the README.md file is broken and leads to 404

I am looking into generating code from the prisma model, but I am failing to find examples on this

**Comment by jasonkuhrt** [comment]
Sorry I'm not sure which link it is that is broken?

**Comment by ranjan-purbey** [comment]
@valecarlos if you are talking about @nexus/schema docs link, I have already submitted a [PR](https://github.com/graphql-nexus/schema/pull/419) for it.
