### ISSUE TITLE
Why in these examples there is apollo / yoga servers

### ISSUE THREAD

**Issue by gustawdaniel** [graphql-nexus/schema#444]
But when I generate app from scratch I do not see any of these servers.

It is totally confusing.

What is relation between

graphql nexus from this page https://nexus.js.org/

and

graphql nexus from this page https://www.nexusjs.org/#/

I would like to use this one:

https://www.nexusjs.org/#/

but unfortunatelly docs is not filled yet.

The only place where is it explained is there:

> https://www.nexusjs.org/#/getting-started/migrate-from-nexus-schema?id=using-nexusschema

But information about 

"""
How to configure makeSchema to generate schema as a file
"""

is not included there, but for prevoius version this was explained on many examples.

**Comment by jasonkuhrt** [comment]
Nexus Schema is a library and Nexus is a framework that builds on top of it.

If you didn't already read https://github.com/graphql-nexus/schema/issues/373.

In Nexus the framework you don't use `makeSchema`.

If you have more questions you can use the [Nexus discussions](https://github.com/graphql-nexus/nexus/discussions).
