### ISSUE TITLE
t.model.foobar({pagination: true}) pagination not exposing args

### ISSUE THREAD

**Issue by johhansantana** [graphql-nexus/schema#453]
Hello, I'm trying to expose the pagination args using `t.model.foobar({pagination: true});` but it seems to only expose `skip`:

<img width="165" alt="Screen Shot 2020-06-19 at 10 45 02 AM" src="https://user-images.githubusercontent.com/9933887/85145131-1afe7900-b21a-11ea-8029-57e037b5910f.png">
<img width="432" alt="Screen Shot 2020-06-19 at 10 45 09 AM" src="https://user-images.githubusercontent.com/9933887/85145134-1b970f80-b21a-11ea-8999-593a674b5136.png">

using `"@nexus/schema": "^0.14.0",`

**Comment by Weakky** [comment]
Hey @johhansantana, I'm pretty sure this issue must be fixed by now. I'm closing it, but feel free to chime in if it's still the case on the latest versions.
