### ISSUE TITLE
Expected <type> to be a objectType, saw GraphQLScalarType

### ISSUE THREAD

**Issue by leemhenson** [graphql-nexus/schema#464]
Hi. I'm trying nexus schema out on an api which was developed schema-first. I used the SDL converter to convert my SDL into nexus typedefs, and now I'm trying to boot the app in order to get it to generate some types. I'm getting this error out which I don't understand:

`Expected FooError to be a objectType, saw GraphQLScalarType`

```ts
const FooErrorCode = enumType({
	name: "FooErrorCode",
	members: ["INTERNAL_SERVER_ERROR"],
});

const FooError = objectType({
	name: "FooError",
	definition(t) {
		t.field("code", { type: FooErrorCode });
	},
});

const FooResult = unionType({
	name: "FooResult",
	definition(t) {
		t.members(FooError, BarSuccess);
		t.resolveType(() => null);
	},
});
```

What am I doing wrong?

**Comment by leemhenson** [comment]
For future me: it turns out this is the error generated when you forget to export something, so that it is not part of the glob that goes into the `types` field on the schema object.

**Comment by platzhersh** [comment]
@leemhenson I know this is an old issue, but can you elaborate what exactly you mean with exporting something to the glob?

**Comment by leemhenson** [comment]
I wish I could remember. 😂  I don't work on that project any more either, so.....sorry.

**Comment by Billcountry** [comment]
Thanks @leemhenson you just saved me hours of work. 

https://github.com/graphql-nexus/nexus/issues/464#issuecomment-667038557

**Comment by igor-smol** [comment]
An example of a situation when this could happen for @platzhersh or anyone interested.

1\. Create a type that references another type. E.g.:

```ts
import { objectType } from "nexus";

export const X = objectType({
  // ...
  definition(t) {
    t.field("y", {
      type: "Y"
      // or type: require("./y").Y, it doesn't matter
    });
  }
});
```

2\. Run nexus's `makeSchema` and pass `types` that don't include the referenced type (`Y` in the previous example) to it.

3\. Since nexus has no idea what the referenced type is, it will throw an error mentioned above.
