### ISSUE TITLE
Pagination paramaters not showing on graphql query

### ISSUE THREAD

**Issue by tamanhquyen** [graphql-nexus/schema#487]
I've using nextjs & prisma & nexus-prisma plugins but I have a problem Pagination paramaters not showing please check image bellow: 
![Capture](https://user-images.githubusercontent.com/6171867/89818011-45621800-db73-11ea-82f2-8fb2be8060e2.PNG)

My queryType 
![image](https://user-images.githubusercontent.com/6171867/89818190-8fe39480-db73-11ea-8e85-315d50927e16.png)

My package.json
![image](https://user-images.githubusercontent.com/6171867/89818099-6cb8e500-db73-11ea-81ff-54728076951c.png)

Please somebody can help!

Thanks.

**Comment by Weakky** [comment]
Hey @tamanhquyen,

I'm pretty sure this issue has been fixed by now. Apologies for the lack of answer, closing now 🙏
