### ISSUE TITLE
publish version with graphql v15

### ISSUE THREAD

**Issue by DerMambo** [graphql-nexus/schema#489]
Hey guys,

I bet you are all busy, but I would still like to ask if you could publish a version (pre-release/next/whatever) that contains the latest version bump of graphql v15. That change is currently in the develop branch. 

Since I am using graphql 15 in a larger monorepo project I got some issues when having to use graphql v14 within the graphql service. All solvable but not really optimal 🤷

**Comment by jasonkuhrt** [comment]
Done for a few weeks now.
