### ISSUE TITLE
Connection Plugin: Incorrect logic for the defaultHasPreviousPage implementation

### ISSUE THREAD

**Issue by nayaabkhan** [graphql-nexus/schema#490]
Hello! And thanks to all involved in contributing to the library. 🙏🏼

### Context

I'd like to report a bug that I encountered with the default implementation of `hasPreviousPage` in the Connection Plugin:
https://github.com/graphql-nexus/schema/blob/0ee644b2343307ef5cff64b46dcc5ead3f4a7c6a/src/plugins/connectionPlugin.ts#L804

Which should be as follows:

```ts
return nodes.length > args.last
```

In the current form, this implementation returns `true` for `hasPreviousPage` when on the first page and paginating backward. The expected value is `false`.

I'd be happy to send over a pull request once given a go. 😄 

### Temporary workaround

Override the `pageInfoFromNodes` in your `t.connection` field with the correct logic.

**Comment by jasonkuhrt** [comment]
PR welcome. Maybe there was a reason it was like this, but can't remember now. If so it should become obvious once you go to update the tests.

**Comment by jasonkuhrt** [comment]
I took a look, @tgriesser designed it this way as per the code comment at https://github.com/graphql-nexus/schema/blob/develop/src/plugins/connectionPlugin.ts#L801-L802.

Please open a feature request if you would like to see this changed. When paginating forward there is logic to fetch +1 to know if there is another page or not. Maybe someone can propose similar default logic for paginating backward.

**Comment by pandanoir** [comment]
Hello @jasonkuhrt .

I've met same issue and seen your comment, but the link for comment is broken. Is [this comment](https://github.com/graphql-nexus/nexus/blob/4d8e37177bb8fb7ddc0a187549a28b1ce7810ce6/src/plugins/connectionPlugin.ts#L1032-L1033) that?
