### ISSUE TITLE
Exposing interfaceTypes in main query does not generate the implementations of this interface in the graphql schema.

### ISSUE THREAD

**Issue by sandrozbinden** [graphql-nexus/schema#501]
# 🐞 bug report

### Affected Package
The issue is caused by package @nexus/schema": "0.15.0" and "graphql": "14.5.8",

### Description
Exposing interfaceTypes in main query does not generate the implementations of this interface in the graphql schema.

## 🔬 Minimal Reproduction
The following code creates a schema.graphql without the Airplane type defined 

```javascript
const Vehicle = interfaceType({
    name: 'Vehicle',
    definition(t) {
        t.string('velocity');
        t.resolveType((item) => null);
    },
});

const Airplane = objectType({
    name: 'Airplane',
    definition(t) {
        t.string('wings');
        t.implements(Vehicle);
    },
});

const Query = objectType({
    name: 'Query',
    definition(t) {
        t.field('Vehicle', {
            type: Vehicle,
            resolve: () => loadVehicle(),
        });
    },
});

export default makeSchema({
    types: [Query],
});`
```

Generates the following schema.graphql:

```graphql
type Query {
    Vehicle: Vehicle!
}

interface Vehicle {
    velocity: String!
}
```

But we expect: 
```graphql
type Airplane implements Vehicle {
    velocity: String!
    wings: String!
}

type Query {
    Vehicle: Vehicle!
}

interface Vehicle {
    velocity: String!
}
```

**Comment by santialbo** [comment]
When you call `makeSchema`, `types` should contain all the types you want to expose on the graphql schema. Otherwise, nexus can't find them. In this case it can find `Vehicle` because it's explicitly used on the `Query` type but `Airplane` isn't.
It's just safer to just include all types and let nexus do the magic.

**Comment by sandrozbinden** [comment]
Hi @santialbo 

Thank you very much for the hint. At first we thought that we would only enter root types there. Now that we have entered our types in `makeSchema`, `types ` everything works as expected.
