### ISSUE TITLE
connectionPlugin doesn't resolve cursorFromNode

### ISSUE THREAD

**Issue by hyochan** [graphql-nexus/schema#504]
Below is our code.
```
import { connectionPlugin, makeSchema } from '@nexus/schema';

import { nexusSchemaPrisma } from 'nexus-plugin-prisma/schema';

export const schema = makeSchema({
  types,
  plugins: [
    nexusSchemaPrisma(),
    connectionPlugin({
      cursorFromNode(node) {
        return node.id;
      },
    }),
  ],
...
```

And usage
```
export const channels = queryField((t) => {
  t.connectionField('channels', {
    type: 'Channel',

    additionalArgs: {
      withMessage: booleanArg(),
    },

    async nodes(_, args, ctx) {
      const { after, before, first, last } = args;

      return ctx.prisma.channel.findMany({
        ...relayToPrismaPagination({
          after, before, first, last,
        }),

        orderBy: { id: 'desc' },
      });
    },
  });
});
```

Above doesn't change the `cursor` to `id` of the node as shown below.
![Screenshot 2020-09-12 at 1 54 30 AM](https://user-images.githubusercontent.com/27461460/92952462-f7ef0880-f49a-11ea-9d72-b986dad71d25.png)

Even tried `cursorFromNode` in `queryField`.  WIP code is [here](https://github.com/dooboolab/hackatalk/pull/256).

Having hard time invalidating caches in `connection` 😩 .

**Comment by Weakky** [comment]
Hey @hyochan, could you elaborate a bit more on the problem here, I'm unfortunately not sure to understand, thanks 🙏

**Comment by raymclee** [comment]
@Weakky I think he expected the cursor = the node id

**Comment by tgriesser** [comment]
The cursor probably shouldn't be the same as `node.id`, but if you really want it to be then you need to set:

```ts
encodeCursor: value => value,
decodeCursor: value => value
```

as part of your config
