### ISSUE TITLE
Call one mutationField inside of another one

### ISSUE THREAD

**Issue by chrissisura** [graphql-nexus/schema#510]
Is it possible to have abstractions in a way, that mutations call other mutations and or querys in order to avoid duplicate code or is there need for a third non-resolver folder with functions in it that you call from outside. What are the best practices here? Any advice is greatly appreciated!

**Comment by Weakky** [comment]
Hey @chrissisura,

`@nexus/schema` doesn't provide any specific abstraction to do that. However, you're free to come up with your own. One of our examples has a lightweight "architecture" which enables decoupling the resolver implementation for the GraphQL API itself. You can check it out here, this should achieve what you're looking for: https://github.com/graphql-nexus/schema/tree/develop/examples/ghost/src/data-sources

**Comment by chrissisura** [comment]
Ok thanks for letting me know!
