### ISSUE TITLE
Configuring auto-launched dev server (or better solution for running configureable server)

### ISSUE THREAD

**Issue by TommyCoding** [graphql-nexus/schema#542]
My situation: on client-side I have a VueJs and Nuxt-based app as frontend which I want to connect to my nexus app as API middleware.  As database backend I use the prisma plugin with nexus.

So the workflow is:    Nuxt and Apollo Client Module (Frontend) <-> Nexus Graphql API (Graphql/HTTP) <-> Database (Prisma)

I am so confused about how to solve specific things in nexus framework as there are so many different tutorials and examples are out there which all seem to rely on different versions of the framework, so that code often isn`t valid anymore. And also the docs are useless sometimes as there seems required code to be missing or it is invalid too.
I know the framework is under heavy development and some things are outdated atm but I really like it so much so I hope you can give me some help here please.

I also want to implement/use the following features of the framework in future for my API:
- Graphql subscriptions
- Authorization (maybe with tokens and Http-based cookies)
- Eventually some HTTP endpoints when GQL is useless (downloading big files to frontend)
- ...

At the moment I got stuck when configuring CORS headers on nexus (GraphQl) server side. I dont know how to do it because when I run nexus in development mode (yarn -s dev) everytime the auto-launched development server instance is ran and I did not found any working example on how to change or configure the underlying server instance.

There are some examples out there running the Graphql server manually with custom code and express, but the it conflicts with the auto-launched dev server as both are starting then. What is the best way (code) of solving that ?

BTW i initially created the project with the installer command "npx nexus" so the necessary configs were created automatically. My current package.config:

```
    "@nexus/schema": "^0.15.0",
    "nexus": "^0.26.1",
    "nexus-plugin-prisma": "^0.18.1",
```

**Comment by Sytten** [comment]
Nexus is EOL, let's give the devs some time to reorganize the documentation around schema, fix namespacing, etc.

**Comment by TommyCoding** [comment]
Sorry I didn`t realize that there are two different projects and I was using EOL nexus **framework**. Just some days after posting I found the information about nexus framework EOL, where things got a bit clearer: https://github.com/prisma-labs/graphql-framework-experiment/issues/1432
I will fully switch over to nexus schema (with prisma layer) which may solve my issues. Thanks.
