### ISSUE TITLE
Create an adoption guide for Next.js users

### ISSUE THREAD

**Issue by jasonkuhrt** [graphql-nexus/schema#543]

**Comment by jasonkuhrt** [comment]
https://prisma.slack.com/archives/CM2LEN7JL/p1603854296246900

**Comment by stefnnn** [comment]
how bumpy should I expect the road to be when coming from nexus-framework (currently integrated with next.js) when migrating to nexus-schema? I'd be happy to help test instructions and try the migration on our project https://github.com/teachen-ch/voty

**Comment by jasonkuhrt** [comment]
@stefnnn not very bumpy
