### ISSUE TITLE
UnionType does not take UnionTypes

### ISSUE THREAD

**Issue by Jomik** [graphql-nexus/schema#550]
It is my understanding that a `union Foo = Bar | Baz` can also be used in a different union `union Bum = Foo | Buz`. But this currently gives the following error `Expected Foo to be a objectType, saw GraphQLUnionType`.

**Comment by tgriesser** [comment]
From the [GraphQL Spec](https://spec.graphql.org/June2018/#UnionMemberTypes):

> The member types of a Union type must all be Object base types; Scalar, Interface and Union types must not be member types of a Union. Similarly, wrapping types must not be member types of a Union.

I'm not sure the reasoning for not allowing unions to be members of unions, but this behavior is in fact spec compliant.

**Comment by Jomik** [comment]
Oh.. I missed that part, I just looked at the BNF and it looked like they just had to be a named type to be part of unions there.. 😅
