### ISSUE TITLE
Date Scalar not working

### ISSUE THREAD

**Issue by cyrus-za** [graphql-nexus/schema#552]
Repo to reproduce:
https://github.com/cyrus-za/prisma-nexus-date-error

```sh
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
User.ts:7:7 - error TS2339: Property 'date' does not exist on type 'ObjectDefinitionBlock<"User">'.

     t.date('createdAt', {
```

**Comment by AhmedElywa** [comment]
your issue in running command tries with this `yarn ts-node --transpile-only index.ts`
you missed `--transpile-only`, so when you start, your command date  not exist, so the compiler failed

**Comment by cyrus-za** [comment]
Thanks that solves it.
