### ISSUE TITLE
Adding to Context

### ISSUE THREAD

**Issue by jonestristand** [graphql-nexus/schema#579]
Hey - might be a very silly issue, but I can't sort out the proper way to add an object to the context. There is an example in Tutorial 3 but in this case explicitly using ApolloServer, and I am not directly using it. I can't seem to find the matching setting by drilling down in nexus.settings.change either. Cheers!

**Comment by yograf** [comment]
What are you using? can you share some code?

**Comment by jonestristand** [comment]
Just the base nexus setup, which I believe uses express and apollo in the background. I'm not sure what the correct way to get down to apollo and add to the context is however. As you can see below, I have a firebase admin object that gets initialized and I'd like to pass it in to the query and mutation resolvers to be used. app.ts below, and then I have separate query and mutation.ts files, and a model file for each type in the schema.

```ts
import * as nexus from 'nexus';
import { prisma } from 'nexus-plugin-prisma';

import * as firebaseAdmin from 'firebase-admin';

// Initialize firebase
const firebaseApp = firebaseAdmin.initializeApp({
  credential: firebaseAdmin.credential.applicationDefault(),
  databaseURL: 'https://$$URL_HERE$$.firebaseio.com'
});

// Set settings for nexus
nexus.settings.change({
  server: {
    port: Number(process.env.WWW_PORT) ?? 4000,
    path: process.env.WWW_PATH ?? '/gql',
    playground:
      process.env.NODE_ENV === 'production'
        ? false
        : { settings: { "editor.cursorShape": "line" } },
    startMessage: (address) => {
      console.log(
        `🚀 Server ready at: http://localhost:${address.port}${address.paths.graphql}`
      );
      if (process.env.NODE_ENV !== 'production')
        console.log(
          `⛱️  GraphQL Playground enabled`
        );
    }
  },
});

nexus.use(prisma());
```

**Comment by jonestristand** [comment]
I just came across the dropping of support for Nexus Framework and I think that underlies the issue I am having. Can someone confirm that this is the case, and that if so the correct way to implement this functionality is to move to nexus-schema on top of apollo server and pass the firebase object in through the apollo server context object?

**Comment by yograf** [comment]
Yep, you are correct. Nexus schema is nice and I really like it but after the doping of Nexus framework and some bugs I have with nexus prisma plugin I'm starting to think about moving to simpler solution like graphql-js
https://medium.com/swlh/graphql-js-vs-typegraphql-vs-graphql-nexus-2a8036deb851

**Comment by jonestristand** [comment]
Yeah the torment of being an early adopter. I have managed to migrate to the nexus/schema setup and it is doing what I need it to do for now, and I do kind of like the finer-grained control. That being said, still significant bugs with reflection and the prisma nexus plugin that are causing some headaches. :-)

I'll close this issue now. Thanks!
