### ISSUE TITLE
Raise minimum required TS version to 4.1

### ISSUE THREAD

**Issue by jasonkuhrt** [graphql-nexus/schema#580]
TS 4.1 will have a lot of new and interesting power for complex type expressions. We should lock in that requirement for Nexus before hitting 1.0. This way we can start to roll out features after without requiring to hit this breaking change _after_ 1.0 so soon.

There might not be any immediate end-user benefits by raising the TS bar to 4.1 however improved internal typings and typegen will be indirectly important to project health and momentum.

**Comment by tgriesser** [comment]
Can't wait to turn on `noUncheckedIndexedAccess` and see how much guarding we need to do in the existing code. Hopefully won't be too bad, but just tried it out for the first time on some projects and it was 😬
