### ISSUE TITLE
Improve nullability & list API

### ISSUE THREAD

**Issue by Weakky** [graphql-nexus/schema#591]
## Motivation

Current API tries to describe nullability & list using booleans.

```ts
t.field('foo', {
  nullable: boolean,
  list: boolean | boolean[]
})
```

Here's how the current API can be used:

```ts
import { objectType } from '@nexus/schema'

export const Test = objectType({
  name: 'Foo',
  definition(t) {
    t.string('a') // String
    t.string('b', { nullable: false }) // String!
    t.string('c', { list: true }) // [String]
    t.string('d', { list: true, nullable: false }) // [String]!
    t.string('e', { list: [true] }) // [String!]
    t.string('f', { nullable: false, list: [true] }) // [String!]!
  }
})
```

This can quickly become very unintuitive. I actually had to quickly jump in a playground to remember the API.

## Proposal n°1

Replace the current API with the following two simple constructors: `nonNull()` & `list()`, inspired from https://docs.graphene-python.org/en/latest/types/list-and-nonnull/.

While its usage is slightly more verbose, it's also much clearer.

**Usage example**:

```ts
import { objectType, list, nonNull } from '@nexus/schema'

objectType({
  name: 'Foo',
  definition(t) {
    t.field('a', { type: 'String' }) // String
    t.field('b', { type: nonNull('String') }) // String!
    t.field('c', { type: list('String') }) // [String]
    t.field('d', { type: list(nonNull('String')) }) // [String!]
    t.field('e', { type: nonNull(list('String')) }) // [String]!
    t.field('f', { type: nonNull(list(nonNull('String'))) }) // [String!]!
  }
})
```

The biggest con with this proposal is that it doesn't seem to support the `t.{scalars}` shorthands at all since the types are now wrapped in `list()` and `nonNull()` types. Here's a quick illustration:

```ts
t.string('myField', { /*no type property, so we can't express list or nullability*/ })
```

Did I maybe miss something that would keep this proposal usable with the scalar shorthand? We _could_ enable something like:

```ts
t.string('somefield', {
  listOrNullability: list(nonNull()) // [String!] - Please, ignore the terrible `listOrNullability` field name, it doesn't matter here
})
```

But I'm not sure that's intuitive either...

## Proposal n°2

The current API already supports shorthand for list fields, using the `t.list.*`. We could expand on the previous idea and allow the following expressions:

```ts
import { objectType } from '@nexus/schema'

objectType({
  name: 'Foo',
  definition(t) {
    t.string('a') // String
    t.nonNull.string('b') // String!
    t.list.string('c') // [String]
    t.list.nonNull.string('d') // [String!]
    t.nonNull.list.string('e') // [String]!
    t.nonNull.list.nonNull.string('f') // [String!]!
  },
})
```

I honestly don't like very much the chaining style of this API, which makes the readability fairly hard. But at least it keeps supporting the scalar shorthands which I find very useful to reduce the boilerplate already created by the code-first paradigm.

## Proposal n°3

It's very unlikely that we'll want that, but just to be exhaustive, we could as well allow the SDL representations:

```ts
import { objectType, list, nonNull } from '@nexus/schema'

objectType({
  name: 'Foo',
  definition(t) {
    t.field('a', { type: 'String' }) // String
    t.field('b', { type: 'String!' }) // String!
    t.field('c', { type: '[String]' }) // [String]
    t.field('d', { type: '[String!]' }) // [String!]
    t.field('e', { type: '[String]!' }) // [String]!
    t.field('f', { type: '[String!]!' }) // [String!]!
  }
})
```

Cons:

- No support for scalar shorthands either
- No support for type reference using the actual values (as opposed to references using type names)
- Could blow up the union type member threshold very quick (which is around 100k I think)
- Cannot type-safely support nested arrays (which could be infinitely nested) without blowing up the union type member threshold even quicker

Let us know if you have better proposals and/or which one you prefer here 🙌

**Comment by jasonkuhrt** [comment]
> Did I maybe miss something that would keep this proposal usable with the scalar shorthand?

```ts
t.list.string('somefield', {}) // [String]
t.nonNull.string('somefield', {}) // String!
t.list.nonNull.string('somefield', {}) // [String!]
t.nonNull.list.nonNull.string('somefield', {}) // [String!]!
```

Playing with some other vocabulary:

```ts
t.guaranteed.string('somefield', {}) // String!
t.list.guaranteed.string('somefield', {}) // [String!]
t.nonNull.list.guaranteed.string('somefield', {}) // [String!]!

t.sure.string('somefield', {}) // String!
t.list.sure.string('somefield', {}) // [String!]
t.sure.list.guaranteed.string('somefield', {}) // [String!]!
```
Also we'll need an inverse. For example imagine the user has global default to be non-nullable.

Again playing with vocabulary:

```ts
t.nullable.string('somefield', {}) // String
t.list.nullable.string('somefield', {}) // [String]
t.nullable.list.nullable.string('somefield', {}) // [String]

t.maybe.string('somefield', {}) // String
t.list.maybe.string('somefield', {}) // [String]
t.maybe.list.maybe.string('somefield', {}) // [String]

t.optional.string('somefield', {}) // String
t.list.optional.string('somefield', {}) // [String]
t.optional.list.optional.string('somefield', {}) // [String]
```

-- edit haha this is your no.2 proposal 🙈

**Comment by Weakky** [comment]
After a call with @jasonkuhrt, here's all the proposal we've found (some overlapping with the current ones):

```ts
// Option 1
t.null.list.nonNull.field('a', {
  type: 'Foo',
  resolve() {}
})

// Option 2
t.field('a', {
  type: nonNull(list(nonNull('Foo'))),
  resolve() {}
})

// Option 3
t.field('a', {
  type: type.nonNull.list.nonNull.ref('Foo'),
  resolve() {}
})

// Option 4 (using proxy)
t.nonNull.list.nonNull.Foo('a', {
  resolve() {}
})
```

**Current preferred choices: 1 & 2** (given the ):

- We think option 1 (`t.list.nonNull.*`) should be what most users should be using so that the API stays symmetrical between scalars shorthand and `t.field`
- Option 2 (`list(nonNull(...))`) will be kept as lower-level primitives that Option 1 will use and that plugins and/or custom use-cases should be using.

@tgriesser WDYT?

**Comment by tgriesser** [comment]
I feel like option 1 starts to get a little confusing / ugly / adds complexity to the builder internals, whereas option 2 is much clearer / explicit. 

I almost wish that the `t.list.` convenience API didn't exist, and we just enforced things always be added as part of the field-level config (similar to #592).

**Comment by Weakky** [comment]
@tgriesser how do you use option 2 with any of the scalar shorthands? eg: `t.string('foo')`

**Comment by tgriesser** [comment]
That's a good point, hadn't considered that. I guess you'd need to be verbose and do:

```ts
t.field('foo', {
  type: nonNull(list(nonNull('String')))
})
```


In that case, if you think it's worth it. I'm fine with option 1, in addition to adding option 2... and so just to clarify `t.null.list.notNull.string('foo')` would evaluate similar to the fn calls, and be `[Foo!]`, correct?

**Comment by jasonkuhrt** [comment]
> and so just to clarify t.null.list.notNull.string('foo') would evaluate similar to the fn calls, and be [Foo!], correct?

`[String!]` I think you mean? If so, yep!

> In that case, if you think it's worth it. 

The other option is removing scalar shorthands altogether and forcing everyone down `.field`. Not saying I favour that but it is technically an option here.

---

We're going to have to decide what this means:

```ts
t.null.list.notNull.field('foo' {
  type: notNull(list('Bar'))
})
```

1. don't allow `.field` to be used with shorthands
2. wrap shorthands around `type` config: `null(list(notNull(nonNull(list('Bar')))))`. Notice the doubling of `nonNull`... pretty confusing, probably a runtime error since that cannot be representing in GraphQL.

---

This is somewhat off topic but it came up in discussing with @Weakky (my wacky ideas not his! hah): On the other hand, with shorthands, the only remaining use case for explicit `type` config by humans (programmatic usage is another story) is object type references. Nexus is so close to supporting shorthands for those too though:

```ts
t.null.list.notNull.Bar('foo' {
  resolve() { ... }
})
```

```graphql
foo: [Bar!]
```

One nice thing is that it gets the API further away from the problem/criticism I just mentioned above. Further because by not using `type` mostly users mostly avoid the case of it+shorthands ambiguity.

**Comment by tgriesser** [comment]
> The other option is removing scalar shorthands altogether and forcing everyone down .field. Not saying I favour that but it is technically an option here.

Yeah, I've definitely thought about it. AFAIK it's what [graphql-ruby does](https://graphql-ruby.org/type_definitions/objects.html#object-classes). I think it's also reasonable to say that if you need to override the nullability / list(ability)? of a type, you just use `t.field` and decorate the type.

> We're going to have to decide what this means:
> 1. don't allow .field to be used with shorthands

Yeah I'd say if we do support this, we'd allow one or the other, not both. Similar to how we currently warn if you do both `t.list` and `list: true`

> Notice the doubling of nonNull... pretty confusing, probably a runtime error since that cannot be representing in GraphQL.

Don't want to do do this (combining chaining + type), but just fyi wrapping nulls in nulls `GraphQLNonNull(GraphQLNonNull(t))` is a no-op in schema definition/construction.

> On the other hand, with shorthands, the only remaining use case for explicit type config by humans (programmatic usage is another story) is object type references. Nexus is so close to supporting shorthands for those too though:

it's potentially visually confusing to have `t.Bar` vs `type: Bar`. The alias is really only intended for frequently accessed scalars `t.date` / `t.json`, or to hide complex logic `t.connectionField`. 

Also, with the alias you lose the jump-to-definition. When you use it on `t.Bar` you go to this abstract auto-generated thing which is already a source of confusion, vs. jumping on `type: Bar` which brings you to the object type def. 

I'd say I find the jump to definition of the field's `type` one of the most important ergonomic dev features when creating a schema, and I wouldn't want to use `t.Bar`. Also, there's many types that are infrequently used types that'd show up in autocomplete, and additionally if you rename the type, you're now calling a non-existent method and things won't run and the types won't update and it becomes a mess.

**Comment by jasonkuhrt** [comment]
> I'd say I find the jump to definition of the field's type one of the most important ergonomic dev features when creating a schema, and I wouldn't want to use t.Bar. Also, there's many types that are infrequently used types that'd show up in autocomplete, and additionally if you rename the type, you're now calling a non-existent method and things won't run and the types won't update and it becomes a mess.

Yeah great points. Overcoming any of this wouldn't be trivial.

> I think it's also reasonable to say that if you need to override the nullability / list(ability)? of a type, you just use t.field and decorate the type.

It feels like creating lists of scalars, or adjusting its nullability, is a pretty common pattern.

I always wonder about this: If a significant part of my codebase is using one style, it has a cognitive cost to be using another style. The fewer use-cases there are for the "sugar" of `t.<scalar>` the less appeal it seems to hold.

Option 3 held some appeal to me because it allowed for not having to learn two APIs. But I realized that option 3 is a pain for programmatic usage, whereas option 2 is good for that.

**Comment by Sytten** [comment]
I have a different proposition. What about converting the `nullable` field to:
```typescript
nullable: boolean | { list: boolean, type: boolean }
```
Basically, `true` means both are nullable and if you need fancy stuff you use the object.
You can make it fancier by detecting if `list: true` in the config and changing the type based on that.
I also agree that the `.list` should not be a thing. I also think `required` should be removed.

**Comment by Sytten** [comment]
@Weakky @jasonkuhrt just making sure my previous comment is not forgotten. I am really not a fan of the type wrapping :/

**Comment by jasonkuhrt** [comment]
@Sytten Hey, Composable functions are the way this is going to go for `type` property configuration. I think there's some strong points in its favour that @tgriesser is fond of. IMO the strongest points are its flexibility and simplicity, very amenable to building higher abstractions with. 

At the same time the short hand chaining will remain in place.

**Comment by mendesbarreto** [comment]
Hello @jasonkuhrt or @Weakky, how are you doing?

A little question for you, does the `required: true or list: true` will be deprecated at some point? 

Thank you
