### ISSUE TITLE
Scalar shorthand methods case should match SDL representation

### ISSUE THREAD

**Issue by jasonkuhrt** [graphql-nexus/schema#600]
In SDL we refer to types of `String` `Bool` `Int` etc. In Nexus we have shorthands for them of `t.string` `t.bool` `t.int` etc.

I think the casing should be consistent so that Nexus declarative API looks a bit closer to SDL. 

So `t.String` `t.Bool` `t.Int` etc. 

It's also more consistent for the fact that `t.string` is shorthand for `type: 'String'`.

It's also an important change if we ever want to have shorthands for all custom types defined in the schema as alluded to in https://github.com/graphql-nexus/schema/issues/591#issuecomment-720872365. Because then we would really want the methods to match their SDL type names case-sensitivity consistently.

**Comment by jasonkuhrt** [comment]
@Weakky @tgriesser wdty?

**Comment by tgriesser** [comment]
Ehhh, I typically reserve capitalized names for constructors in js... but that aside - not sure I see a strong value in making this change. See comments re: `t.Bar` in #591

**Comment by jasonkuhrt** [comment]
@tgriesser Yep I think without `t.Bar` this is a lot less appealing as an idea. Will close, people can chime in if ever they want to see the idea discussed again.
