### ISSUE TITLE
Enable SDL output by default

### ISSUE THREAD

**Issue by jasonkuhrt** [graphql-nexus/schema#632]
I think by default the SDL output should be enabled and should output to the first ancestor directory where a `package.json` is found. The file name should default to `schema.graphql`.

**Comment by jasonkuhrt** [comment]
CC @Weakky @tgriesser

**Comment by tgriesser** [comment]
Sounds reasonable. Could just default it to `path.join(process.cwd(), schema.graphql)`?

**Comment by jasonkuhrt** [comment]
Using `process.cwd()` would certainly make for an easier time doing package linking 😓.

It feels a bit less deterministic to me.

Thinking about monorepos, wondering if there are concrete tradeoffs to either approach.

**Comment by tgriesser** [comment]
> Thinking about monorepos, wondering if there are concrete tradeoffs to either approach.

Only thinking of this as a default, you'd generally want to configure it yourself.
