### ISSUE TITLE
Easier management of root type contributions

### ISSUE THREAD

**Issue by jasonkuhrt** [graphql-nexus/schema#636]
Here are some things I would like users to not have to think about:

- I haven't defined a Query type yet, can I use QueryField?
- I haven't defined a Query type yet, can I use extendType with it?
- I want to modularize my schema, can I use `Query` type repeatedly and have it merge?

Here's what I've been thinking about; Multiple calls to root types get merged:

```ts
// A.ts
export const QueryA = queryType({ ... })
```
```ts
// B.ts
export const QueryB = queryType({ ... })
```

I suspect in almost all cases this would be exactly the desired functionality.

On the config properties:

- `definition` – merging this is easy

- `description` – append, order determined by order Nexus sees them (e.g. config property `types` array items order)

- `nonNullDefaults` – this doesn't need to merge, it can just stay local, which makes perfect sense IMO 

- `rootTyping` – this I'm not sure about. Can we just keep it local? I don't see how since the typings are global... Otherwise it is a sharing situation and any that set it affect all others. And if multiple set it then last one wins (same definition of order as explained for `description`). I am not very happy with the behaviour here but two things make me not mind:

	1. In vast majority of cases backing type for root types is `undefined`
	2. jsdoc can explain the quirks

**Comment by jasonkuhrt** [comment]
WDTY @Weakky @tgriesser

**Comment by jasonkuhrt** [comment]
I just realized that `extendType` doesn't require the original type to have been defined. That's great.

So now the main difference left in this proposal is:

```ts
queryType({ definition(){ ... } })

// vs

extendType({ type: 'Query', definition(){ ... } })
```

Not a big difference...

And a trivial way to cut the difference yet further:

```ts
queryType({ definition(){ ... } })

// vs

extendQueryType({ definition(){ ... } })
```

I don't know if then the new merging behaviour I'm proposing is worth it.

If we wanted to cut the difference further we would have to do this for `extendType`:

- allow it to specify `NonNullDefaults`
- allow it to specify `description`

**Comment by tgriesser** [comment]
Isn't this what `queryField` does?

**Comment by ricardoalmeida** [comment]
What's exactly the use case of having multiple `queryType`s? Is it to avoid a bigger schema.ts? In this case, I'd like to see Nexus a little bit more (not that much) opinionated, helping users to split `queries`, `mutations` and `object types` into different files since the beginning.

I use `extendType` basically for joining graphs (different projects) in the same gateway endpoint. I try to avoid using it inside the same project because we can end up in weird cases of inheritance, circular dependencies, and so on. BTW, the nexus documentation about `extendType` could be improved.

Back to the question, if my project grows enough and I see the need of having to split `queryType`, I vote for just defining `queryType`s where I need and let the framework merge them for me.

**Comment by jasonkuhrt** [comment]
@tgriesser ah I forgot this worked:

```ts
export const Mutation = mutationField((t) => {
  t.crud.createOneBlog()
  t.crud.updateManyBlog()
})
```

The naming is a tad surprising here.

![image](https://user-images.githubusercontent.com/284476/99588992-5b287a00-29b9-11eb-909b-947839fa8f9d.png)

Aside: 
  - Some jsdoc would help a lot.
  - Also although there it is overloaded the VSC ui doesn't show the UI for navigating the overloads... Do you know why that might be?

Do you think this variant of mutation field is worth it from an API surface area perspective?

![image](https://user-images.githubusercontent.com/284476/99589308-cbcf9680-29b9-11eb-9519-07ccf25aaf32.png)

I feel like the object form with the very consistent `definition` method might be good enough...

And if we do want to keep both forms, do you think the overload approach is the right way here?

For example if `extendType` gets the additions I was mentioning before `nonNullDefaults` etc. then there becomes a clear difference in functionality:

```ts
extendType({
  type: 'Mutation',
  nonNullDefaults: ...,
  definition(t) {
    t...
  }
})

// and, built over ^, this --v

extendMutationType({
  nonNullDefaults: ...,
  definition(t) {
    t...
  }
})

// which clearly allows capability––the type config––not possible in this API

mutationField(t => {})
mutationField('foo', {})

```

**Comment by tgriesser** [comment]
> What's exactly the use case of having multiple queryTypes? Is it to avoid a bigger schema.ts? In this case, I'd like to see Nexus Schema a little bit more (not that much) opinionated, helping users to split queries, mutations and object types into different files since the beginning.

@ricardoalmeida FWIW, for a monolithic schema, this is the directory structure I generally use:

<img width="153" alt="Untitled2" src="https://user-images.githubusercontent.com/154748/99606148-2c210100-29d7-11eb-8254-d41f7e952135.png">

1 folder per "graphql type", 1 file per top-level `mutation` / `query` / `subscription`, generally 1 file per `objectType`, `interfaceType`, `enumType`, etc...

I only use [`queryField`](https://nexusjs.org/docs/api/query-field) / [`mutationField`](https://nexusjs.org/docs/api/mutation-field) / [`subscriptionField`](https://nexusjs.org/docs/api/subscription-field). Not sure how well this would work for joining graphs across projects but just thought it was worth sharing.

GraphQL types are for definition only, all logic exists in the `context`... the context (we call it DataContext) is then responsible for wrangling all of the different services, etc.

> Some jsdoc would help a lot.

I agree, feel free to add some. Maybe something that matches the docs? It shows up for me before any arguments are supplied:

> Also although there it is overloaded the VSC ui doesn't show the UI for navigating the overloads... Do you know why that might be?

![image](https://user-images.githubusercontent.com/154748/99606735-54f5c600-29d8-11eb-830b-a4966312b6af.png)

> Do you think this variant of mutation field is worth it from an API surface area perspective?

Which variant are you referring to? I think the current form works great. As I mentioned above, I only ever use `mutationField`, so if I need to express something like a `connectionField`, it's the only way to do it. 

Not sure I see the value of making any changes to these apis personally.

**Comment by jasonkuhrt** [comment]
> Not sure I see the value of making any changes to these apis personally.

One limitation right now is that `extendType` does not have access to type configuration like `nonNullDefaults`. And I've seen use-cases for plugins to add type configuration too. It would be neat if extendType maintained access to it.

**Comment by tgriesser** [comment]
`nonNullDefaults` is a pretty powerful API. I don't know that you'd want to "extend" a type and have that being something that might get changed for multiple types, especially on the root level - unless you're thinking that it would apply just to the fields defined within that `extendType`, in which case that seems more reasonable to add support for, though I don't think it'd be something I'd find myself reaching for personally.

**Comment by jasonkuhrt** [comment]
> unless you're thinking that it would apply just to the fields defined within that extendType, in which case that seems more reasonable to add support for, though I don't think it'd be something I'd find myself reaching for personally.

Yep, was thinking this.

I am going to close this issue as the proposal doesn't seem strong enough to warrant all the discussion and internal change.

If it was cheap to do I would say `mutationType` `queryType` `subscriptionType` should merge and thus make `mutationField` `subscriptionField` `queryField` obsolete, thus simplifying the API surface area at the "cost" of increasing the semantic complexity of those three functions. I think the trade would be worth it because I cannot think of a use-case for non-merging `mutationType` `queryType` `subscriptionType`, thus the "semantic complexity" would be none since its what (I think) would be expected/most intuitive anyways.

All that said, I'm worried achieving this will be too costly in terms of internal change and discussion. I think there are more important things to do for 1.0 than this...
