### ISSUE TITLE
abstractTypeStrategies not available

### ISSUE THREAD

**Issue by Jomik** [graphql-nexus/schema#669]
We are really looking forward to being able to use `__typename` in our project, and got really happy when we saw the change in the documentation.
https://nexusjs.org/docs/guides/abstract-types#picking-your-strategy-or-strategies
Sadly it seems like the latest release, 0.18, was pushed out the day _before_ the relevant PR was merged 😞 
Is it possible for a new release to be pushed with these changes?
Alternatively I think it is very confusing that the documentation is updated out of line with the latest released package, perhaps that should be changed?

EDIT: Realized that we can use the `next` tag to get this feature 👍  Confusion still stands with the documentation.

**Comment by jasonkuhrt** [comment]
0.19 has been cut as well.
