### ISSUE TITLE
connectionPlugin breaks with 0.19

### ISSUE THREAD

**Issue by Jomik** [graphql-nexus/schema#670]
We have `nonNullDefaults.input = true` in our project. But that now results in all `connectionPlugin` arguments to also be non null.
This was not the case previously, and `connectionPlugin` should probably be explicit in its requirements.
There is a similar case for `nonNullDefaults.output = true` where it sets `PageInfo.startCursor/endCursor` to be non-nullable

**Comment by tgriesser** [comment]
👍 check #671

**Comment by Jomik** [comment]
Awesome!

**Comment by Jomik** [comment]
I guess we should mention that this is actually an issue in the newest release 0.19 😅
