### ISSUE TITLE
connectionPlugin type changes in 0.19.1

### ISSUE THREAD

**Issue by Jomik** [graphql-nexus/schema#672]
We have some further changes in the output types for the `Connection` type, as seen below.
This does not break the clients, but it imposes further restrictions.
I.e. if resolving one of the `T` types fail, then the entire connection will fail as a result, as the node/edge is not nullable anymore.
```diff
type TConnection {
- edges: [TEdge]
+ edges: [TEdge!]!
- nodes: [T]!
+ nodes: [T!]!
  pageInfo: PageInfo!
}
```

**Comment by tgriesser** [comment]
What nullability settings do you have configured?

**Comment by Jomik** [comment]
Input and output are set to default to non null. Same as in #670

**Comment by tgriesser** [comment]
Yeah, I'd argue that the previous behavior was broken and ^ should have been the actual correct behavior, but there's now an ability to configure `nonNullDefaults` on the `connectionPlugin` its-self. Can you give that a shot and see if it gets to what you're after?
