### ISSUE TITLE
How to set extensions on a type?

### ISSUE THREAD

**Issue by benjixx** [graphql-nexus/schema#683]
I found out that it is possible to extend the extensions on a field using the queryComplexityPlugin as a blueprint.
But now I would like to do the same for a type as well.

For my particular use case I am trying to use JoinMonster with @nexus/schema. For this to work JoinMonster (starting with version 3.0.0, see https://github.com/join-monster/join-monster/blob/master/docs/CHANGELOG.md#v300) requires to use the GraphQL extensions property introduced in GraphQL v15.

As a simple solution I tried to extend the queryComplexityPlugin example and in ```onCreateFieldResolver(config)``` run the following code to update the type extensions config:

```
const joinMonsterConfigOnType =
    config.parentTypeConfig.extensions?.nexus?.config.joinMonster;

if (joinMonsterConfigOnType != null) {
    config.parentTypeConfig.extensions = {
        ...config.parentTypeConfig.extensions,
        joinMonster: joinMonsterConfigOnType,
    } as any;
}
```

But it looks like Nexus is overwriting the type's extensions later on with its own. Could be this location here: https://github.com/graphql-nexus/schema/blob/develop/src/builder.ts#L963

Any help would be much appreciated.

**Comment by tgriesser** [comment]
I was wondering when someone was going to bring up an issue for this 😄. 

I suppose it'd be as simple as adding an `extensions` property on all the possible locations you'd normally have them in graphql-js and merging them, which would provide a naive way of adding metadata if you needed to for tools like joinMonster without a nexus plugin:

```ts
objectType({
  extensions: {
    joinMonster: {
      sqlTable: 'users',
      uniqueKey: 'id'
    }
  }
})
```

And then if you wanted to, you could build a nexus plugin which supported them as topLevel properties w/ proper typings:

```ts
objectType({
  joinMonsterTable: 'users',
})
```

Regardless, we shouldn't be discarding this info - will work on a patch for this

**Comment by tgriesser** [comment]
@benjixx can you check out the changes in https://github.com/graphql-nexus/schema/pull/684 (published as a npm release with tag `@nexus/schema@0.0.0-pr.684.1.187f285`) and see if they support what you're after?

**Comment by benjixx** [comment]
Hey @tgriesser, thanks for the fast solution. I just tried the tag you mentioned above, and it works like a charm.

I am now able to do something like this without writing any additional plugin:
```
const User = objectType({
  name: "User",
  extensions: {
    joinMonster: {
      sqlTable: "USERS",
      uniqueKey: "USER_ID",
    },
  },

  definition(t) {
    t.id("id", {
      extensions: {
        joinMonster: {
          sqlColumn: "USER_ID",
        },
      },
    });
  },
});
```

Thanks a ton! 👍
