### ISSUE TITLE
Site docs certificate expired

### ISSUE THREAD

**Issue by zeyuri** [graphql-nexus/schema#688]
Hello,

I was browsing your Documentation website in the last feel days and noticed that today 30/11/2020 the Lets Encrypt Certificate expired, so users are receiving a warning on the site.

**Comment by stjosh** [comment]
Seems that it has been resolved just a few minutes ago.

**Comment by benedict-jackson** [comment]
I'm still getting warnings

**Comment by jasonkuhrt** [comment]
Thanks for reporting. It was an intermittent issue caused by Netlify, not in our control.
