### ISSUE TITLE
Rename default relay connection api builder method from "connectField" to just "connection"

### ISSUE THREAD

**Issue by jasonkuhrt** [graphql-nexus/schema#689]
Instead of:

```ts
t.connectionField
```

How about just:

```ts
t.connection
```

WDTY @tgriesser @Weakky ?

**Comment by Weakky** [comment]
I personally don't care that much. It depends on which angle you look at it, but I like the symmetry between `t.field` and `t.connectionField`.

I see how there's no symmetry with `t.<scalar>` nor `t.<model|crud>`, but, given that in both cases you'd start typing `t.connection[...]`, IntelliSense will suggest you `t.connectionField`.

IIRC though, it used to be called `t.connection`. Not sure it's worth a breaking change but don't have a strong opinion

**Comment by tgriesser** [comment]
Eh, I remember going back and forth, specifically landed on `connectionField` (as @Weakky mentioned) for symmetry w/ `field`, did some user research and it seemed `connectionField` sounded clearer as to what it was doing.

You can also change it if you want `connectionPlugin({ nexusFieldName: 'connection', })`
