### ISSUE TITLE
improved nullability defaults configuration

### ISSUE THREAD

**Issue by jasonkuhrt** [graphql-nexus/schema#702]
Current system:

```ts
type NonNullDefaults = {
  input: boolean
  output: boolean
}
```

The current system is difficult to reason about because:

- `input` / `output` isn't readily explained anywhere so the value being just a boolean is confusing
- Double negative `nonNull` + `output: false` requires too much 🧠 work
- `Defaults` suffix should be implied, as per the pattern we use in other areas like `abstractTypes` configuration and nexus prisma plugin, where the layers of global and type are clear upon use.

Proposed:

```ts
type Nullability = { // and config property name: nullability
  inputs: 'required' | 'optional'
  outputs: 'guaranteed' | 'nullable'
}
```

Why:

- self-documenting semantics with string literals
- no double negative
- less wordy "nullability" vs "nonNullDefaults" and aligned with website guide section

**Comment by jasonkuhrt** [comment]
@tgriesser @weakky wdty?

**Comment by tgriesser** [comment]
Discussed in Slack, going to keep this as is.
