### ISSUE TITLE
Cannot use Connection Field with unions

### ISSUE THREAD

**Issue by shreyas44** [graphql-nexus/schema#705]
When I try to use `t.connectionField` in the definition of a `unionType` I get a `Property 'connectionField' does not exist on type 'UnionDefinitionBlock'` error.

Example:
```ts
const CharacterInterface = unionType({
  name: "Character",
  definition(t) {
    t.connectionField("friends", {
      type: "Character"
      nodes(root, args, ctx) {
        return ["hello", "hello"]
      }
    })
  }
})
```

**Update**:
I just realised that you can't define a field inside the definition of a Union. 
Although in the query we would have to query them in separate fragments, in some cases some fields might have common resolvers, in which case it's better to write them once in the union definition rather than write them separately each time in the definition of every type that's a part of the union. Is there something that I'm missing here?

**Comment by tgriesser** [comment]
> Although in the query we would have to query them in separate fragments, in some cases some fields might have common resolvers, in which case it's better to write them once in the union definition rather than write them separately each time in the definition of every type that's a part of the union. Is there something that I'm missing here?


Sounds like you're describing an [`interfaceType`](https://graphql.org/learn/schema/#interfaces).

**Comment by shreyas44** [comment]
@tgriesser Yup, as I typed it out I realised that I should be using an `interface` instead of a `union`. Sorry for the trouble 🙂
